/**
 * Linear Integration for Documentation Quality Issues
 * Auto-create Linear issues for broken links and quality problems
 */

import { QualityIssue, QualityReport } from './documentation-quality';

export interface LinearConfig {
    teamId?: string;
    projectId?: string;
    labelIds?: string[];
    createIssues: boolean;
}

/**
 * Create Linear issue for documentation quality problems
 */
export async function createQualityIssue(
    issue: QualityIssue,
    config: LinearConfig
): Promise<string | null> {
    if (!config.createIssues) {
        return null;
    }

    const title = formatIssueTitle(issue);
    const description = formatIssueDescription(issue);

    try {
        // Note: This would use MCP Linear tools in a real implementation
        // For now, we'll simulate the creation and show what would be created
        console.log(`📝 Would create Linear issue: ${title}`);
        console.log(`   Project: Documentation Quality & Maintenance`);
        console.log(`   Priority: ${getPriorityFromSeverity(issue.severity)}`);
        console.log(`   Labels: documentation, maintenance, ${issue.type}`);

        return `MOCK-${Date.now()}`;
    } catch (error) {
        console.error('Failed to create Linear issue:', error);
        return null;
    }
}

/**
 * Process quality report and create Linear issues for high-priority problems
 */
export async function processQualityReport(
    report: QualityReport,
    config: LinearConfig
): Promise<{ created: number; skipped: number }> {
    let created = 0;
    let skipped = 0;

    // Only create issues for medium/high severity problems
    const highPriorityIssues = report.issues.filter(
        issue => issue.severity === 'medium' || issue.severity === 'high'
    );

    for (const issue of highPriorityIssues) {
        const issueId = await createQualityIssue(issue, config);

        if (issueId) {
            created++;
            console.log(`✅ Created issue ${issueId} for ${issue.file}`);
        } else {
            skipped++;
        }
    }

    return { created, skipped };
}

/**
 * Format issue title for Linear
 */
function formatIssueTitle(issue: QualityIssue): string {
    switch (issue.type) {
        case 'broken-link':
            return `[Docs] Fix broken link in ${issue.file}`;
        case 'stale-content':
            return `[Docs] Review stale content in ${issue.file}`;
        default:
            return `[Docs] Quality issue in ${issue.file}`;
    }
}

/**
 * Format issue description for Linear
 */
function formatIssueDescription(issue: QualityIssue): string {
    let description = `## Documentation Quality Issue\n\n`;
    description += `**Type:** ${issue.type}\n`;
    description += `**File:** \`${issue.file}\`\n`;

    if (issue.line) {
        description += `**Line:** ${issue.line}\n`;
    }

    description += `**Severity:** ${issue.severity}\n`;
    description += `**Auto-fixable:** ${issue.autoFixable ? 'Yes' : 'No'}\n\n`;
    description += `**Description:** ${issue.description}\n\n`;

    if (issue.type === 'broken-link') {
        description += `### Action Required\n`;
        description += `- [ ] Check if the linked file was moved or renamed\n`;
        description += `- [ ] Update the link path or remove if no longer needed\n`;
        description += `- [ ] Verify the link works after fixing\n`;
    } else if (issue.type === 'stale-content') {
        description += `### Action Required\n`;
        description += `- [ ] Review content for accuracy and relevance\n`;
        description += `- [ ] Update outdated information\n`;
        description += `- [ ] Archive or remove if no longer needed\n`;
    }

    description += `\n---\n*Auto-generated by documentation quality system*`;

    return description;
}

/**
 * Default configuration for solo dev workflow
 */
export const defaultQualityConfig: LinearConfig = {
    createIssues: true,
    teamId: '24c209ab-be6a-4e90-94f7-1b3ed26a737a', // Lumina-Product team
    projectId: 'cebdd534-b169-4942-a070-6ab6a471b79b', // Documentation Quality & Maintenance project
    labelIds: ['documentation', 'maintenance']
};
/**

 * Map issue severity to Linear priority
 */
function getPriorityFromSeverity(severity: 'low' | 'medium' | 'high'): number {
    switch (severity) {
        case 'high': return 2; // High priority
        case 'medium': return 3; // Normal priority  
        case 'low': return 4; // Low priority
        default: return 3;
    }
}